apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: videorank-dev
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: videorank-api-values
    files:
      - values.yaml
resources:
  - release.yaml

