image:
  repository: europe-west1-docker.pkg.dev/videorank-mlops-werpo78/videorank/videorank-api
  tag: manual-2f38e4f
  digest: sha256:7483cc472254315575b028e8b049d95abd187eb39f3144445708d87de3a34d80
  pullPolicy: IfNotPresent

env:
  VIDEORANK_ENV: dev
  GOOGLE_CLOUD_PROJECT: videorank-mlops-werpo78
  GCP_REGION: europe-west1
  VIDEORANK_BQ_DATASET: videorank
  VIDEORANK_MODEL_PATH: src/videorank/resources/seed_model.json

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
