apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: videorank-api
spec:
  interval: 10m
  chart:
    spec:
      chart: ./apps/videorank-api/chart
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: videorank-api-values
      valuesKey: values.yaml
  install:
    remediation:
      retries: 2
  upgrade:
    remediation:
      retries: 2
