apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: videorank-dev
labels:
  - pairs:
      app.kubernetes.io/part-of: videorank
      app.kubernetes.io/component: api
      environment: dev
    includeSelectors: false
commonAnnotations:
  app.kubernetes.io/managed-by: flux
  gitops.toolkit.fluxcd.io/repository: videorank-mlops-config
  gitops.toolkit.fluxcd.io/environment: dev
configMapGenerator:
  - name: videorank-api-values
    files:
      - values.yaml
resources:
  - ../../base
patches:
  - path: release-patch.yaml
