image:
  repository: europe-west1-docker.pkg.dev/videorank-mlops-werpo78/videorank/videorank-api
  tag: manual-2f38e4f
  digest: sha256:0ab1568fc186ac0a06abbe1dda2b9844b75f4105360db196aa473e90f6e9b037
  pullPolicy: IfNotPresent
env:
  VIDEORANK_ENV: dev
  GOOGLE_CLOUD_PROJECT: videorank-mlops-werpo78
  GCP_REGION: europe-west1
  VIDEORANK_BQ_DATASET: videorank
  VIDEORANK_MODEL_PATH: src/videorank/resources/seed_model.json
  VIDEORANK_MODEL_URI: ''
  VIDEORANK_MODEL_VERSION: seed-local-test
  VIDEORANK_VERTEX_MODEL_RESOURCE: ''
  VIDEORANK_DATA_SNAPSHOT_ID: ''
  VIDEORANK_MODEL_GIT_SHA: ''
  VIDEORANK_MODEL_PROMOTED_AT: ''
  VIDEORANK_MODEL_PROMOTION_REASON: ''
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
