image:
  repository: europe-west1-docker.pkg.dev/videorank-mlops-werpo78/videorank/videorank-api # {"$imagepolicy": "flux-system:videorank-api:name"}
  tag: main-5-9a67722 # {"$imagepolicy": "flux-system:videorank-api:tag"}
  digest: sha256:6ac877e1650b44dd454531246423749ff96721d287637a32e29ea2bf7278c837 # {"$imagepolicy": "flux-system:videorank-api:digest"}
  pullPolicy: IfNotPresent
env:
  VIDEORANK_ENV: dev
  GOOGLE_CLOUD_PROJECT: videorank-mlops-werpo78
  GCP_REGION: europe-west1
  VIDEORANK_BQ_DATASET: videorank
  VIDEORANK_MODEL_PATH: src/videorank/resources/seed_model.json
  VIDEORANK_MODEL_URI: ''
  VIDEORANK_MODEL_VERSION: seed-local-test
  VIDEORANK_VERTEX_MODEL_RESOURCE: ''
  VIDEORANK_DATA_SNAPSHOT_ID: ''
  VIDEORANK_MODEL_GIT_SHA: ''
  VIDEORANK_MODEL_PROMOTED_AT: ''
  VIDEORANK_MODEL_PROMOTION_REASON: ''
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
