image:
  repository: europe-west1-docker.pkg.dev/videorank-mlops-werpo78/videorank/videorank-api # {"$imagepolicy": "flux-system:videorank-api:name"}
  tag: main-6-e300aac # {"$imagepolicy": "flux-system:videorank-api:tag"}
  digest: sha256:a26bb5e68a7df78323eee86aa7f8cc8ef9cd907062124f811c733838f0babe0e # {"$imagepolicy": "flux-system:videorank-api:digest"}
  pullPolicy: IfNotPresent
env:
  VIDEORANK_ENV: dev
  GOOGLE_CLOUD_PROJECT: videorank-mlops-werpo78
  GCP_REGION: europe-west1
  VIDEORANK_BQ_DATASET: videorank
  VIDEORANK_MODEL_PATH: src/videorank/resources/seed_model.json
  VIDEORANK_MODEL_URI: ''
  VIDEORANK_MODEL_VERSION: seed-local-test
  VIDEORANK_VERTEX_MODEL_RESOURCE: ''
  VIDEORANK_DATA_SNAPSHOT_ID: ''
  VIDEORANK_MODEL_GIT_SHA: ''
  VIDEORANK_MODEL_PROMOTED_AT: ''
  VIDEORANK_MODEL_PROMOTION_REASON: ''
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
